[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"
authors = ["Gunnar Westerling <gunnarwesterling@gmail.com>"]

[dependencies]
bootloader = "0.9.23"

[profile.release]
opt-level = 2
lto = true