[build]
target = "x86_64-unknown-none"
rustflags= "-C relocation-model=dynamic-no-pic -C link-args=-no-pie"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"